[package]
name = "rmus-dl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
reqwest = { version = "0.13", features = ["cookies", "form"] }
scraper = { version = "0.27" }
tokio = { version = "1.53", features = ["full"] }
regex = { version = "1.13" }
anyhow = { version = "1.0" }
rand = { version = "0.10" }
thiserror = { version = "2.0" }
dialoguer = { version = "0.12" }
lofty = { version = "0.24" }
indicatif = { version = "0.18" }
